/**
 * Static capability catalog returned by `get_capabilities`. Curated by hand
 * (NOT auto-derived from the tool registry) so we can group tools by
 * intent, name the entities clearly, and ship common-workflow recipes that
 * an LLM client can read and follow without having to compose them from
 * the raw tool descriptions.
 *
 * When you add a new tool: also add it to the right bucket below. The
 * shape is fixed; only the contents grow. Keeping this hand-curated means
 * `get_capabilities` stays a thoughtful API rather than an autogenerated
 * data dump — but it does mean we need a unit test to fail-loud when a
 * registered tool isn't catalogued (see capabilities.test.ts).
 */

import { MCP_VERSION } from "./version.js";

export type CapabilitiesEntity =
  | "user"
  | "nutrition_phase"
  | "meal"
  | "stored_meal"
  | "alcohol"
  | "body_weight"
  | "cardio"
  | "sleep"
  | "steps"
  | "workout"
  | "workout_template"
  | "exercise"
  | "exercise_group"
  | "untracked_period"
  | "accomplishment"
  | "admin";

export type CapabilitiesResponse = {
  /** Server name/version, mirrored from the SDK init payload for convenience. */
  server: { name: string; version: string };
  /** The single tool a fresh client should call first to orient + get a next action. */
  recommended_entrypoint: string;
  /** High-level conventions that apply to every tool. */
  conventions: {
    timezone_handling: string;
    date_format: string;
    timestamp_format: string;
    weights_unit: string;
    food_weights: string;
    idempotency: string;
  };
  /** All entities Almanac tracks, with a one-line summary each. */
  entities: Array<{
    name: CapabilitiesEntity;
    summary: string;
  }>;
  /**
   * CRUD-style tool mapping per entity. Tools that don't fit CRUD (signal
   * readers, recommenders, status snapshots) live in `tools_other`.
   */
  tools_by_entity: Record<
    CapabilitiesEntity,
    Partial<{
      create: string[];
      read: string[];
      update: string[];
      delete: string[];
    }>
  >;
  /** Tools that don't belong to a single entity. */
  tools_other: Array<{ name: string; summary: string }>;
  /** Hand-curated recipes. Each is a short ordered sequence of tool calls. */
  common_workflows: Array<{
    name: string;
    when: string;
    steps: string[];
  }>;
};

export const ALMANAC_CAPABILITIES: CapabilitiesResponse = {
  server: { name: "almanac", version: MCP_VERSION },
  recommended_entrypoint: "get_next_best_action",
  conventions: {
    timezone_handling:
      "Naked-local timestamps (e.g. '2026-05-21T18:30:00') are interpreted in the user's profile timezone. Pass Z or an explicit offset only when the user gave one.",
    date_format: "YYYY-MM-DD",
    timestamp_format: "ISO 8601",
    weights_unit:
      "All persisted weights are in kg. The user's `preferred_unit_system` (metric|imperial) is for display only — convert at the UI layer.",
    food_weights:
      "Meal kcal/protein/carb/fat are totals for the eaten portion. No raw-vs-cooked distinction is enforced; treat what the user said as authoritative.",
    idempotency:
      "log_meal, log_cardio, log_weight, log_alcohol, log_sleep, log_steps are idempotent on payload-hash (safe to retry). log_workout is NOT idempotent (spec §6.4) — every call creates a new workout row.",
  },
  entities: [
    {
      name: "user",
      summary:
        "The account this connection is authenticated as. Holds profile (name, dob, height_cm, sex, preferred_unit_system, timezone). Required for TDEE math, unit display, and timestamp resolution.",
    },
    {
      name: "nutrition_phase",
      summary:
        "A nutrition period with `phase_type` ('cut' | 'bulk' | 'maintenance'), a TDEE snapshot (`tdee_at_phase_start`, `tdee_source`), a signed `deficit_kcal`, the derived `daily_kcal_target`, macro split (`base_protein_g`, `base_carb_g`, `base_fat_g`), and a start/end date. The four TDEE-refactor fields are populated on every new phase and the currently-active phase; older historical phases may carry null on those four (but `daily_kcal_target` is always non-null — it's the rename of the legacy `base_kcal`). At most one phase is active per user; start_nutrition_phase closes any previous active phase.",
    },
    {
      name: "meal",
      summary:
        "A single eating event with kcal + macros. Multiple per day. Drives daily-target math and contributes to today.kcal_in.",
    },
    {
      name: "stored_meal",
      summary:
        "A reusable meal definition in the user's saved-meal library (name + macros + optional description). Timeless — defining one does NOT log an eating event. `define_stored_meal` upserts on name; `log_meal_from_stored` copies one into a real meal. Use the library when the user refers to a 'usual'/'saved' meal.",
    },
    {
      name: "alcohol",
      summary:
        "An alcohol session (one or more drinks at a single occasion). Counted separately from food kcal in energy_balance (kcal_from_alcohol) but rolled into the daily kcal_in total.",
    },
    {
      name: "body_weight",
      summary:
        "A weigh-in. Drives TDEE calibration: <14 readings → TDEE basis='profile_baseline' (guess); ≥14 → 'measured_intake' (real). Also feeds trend_weight smoothing.",
    },
    {
      name: "cardio",
      summary:
        "A cardio session (run, bike, etc). When avg_hr + duration_min are present, the response carries a kcal_estimate (midpoint of Keytel + METs) and an estimate_warning if user-reported est_kcal differs by >20%.",
    },
    {
      name: "sleep",
      summary: "A nightly sleep log (hours + quality 1-5). Drives the sleep_debt signal.",
    },
    {
      name: "steps",
      summary:
        "A daily step count (one row per calendar date, upserted). Drives a small NEAT kcal estimate (derived from latest body weight when not supplied) that feeds TDEE adherence.",
    },
    {
      name: "workout",
      summary:
        "A resistance-training session. Contains 1+ exercise instances, each with 1+ sets (reps, weight_kg). Refreshes per-group stim_state (muscle-group recovery, NOT caffeine/stimulants — naming is unfortunate).",
    },
    {
      name: "workout_template",
      summary:
        "A reusable workout plan (e.g. 'PUSH A') with planned exercises. log_workout can hydrate from a template + record deviations (skip / override_sets / add).",
    },
    {
      name: "exercise",
      summary: "A named movement (e.g. 'Bench Press') belonging to one exercise_group.",
    },
    {
      name: "exercise_group",
      summary:
        "A muscle-group bucket ('Push', 'Pull', 'Legs', 'Chest'…). Drives stim_state — one state per group, tracking how recently it was hit.",
    },
    {
      name: "untracked_period",
      summary:
        "A dated range (vacation/sick/deload) the user wasn't logging. Excludes those days from TDEE back-calc, suppresses staleness/backfill nudges over the range, and surfaces a returning-from-gap signal. Has no update verb — delete and recreate to correct.",
    },
    {
      name: "accomplishment",
      summary:
        "A derived, persisted 'win' (logging streak, workout consistency, target-adherence streak, weight milestone, the TDEE-calibration milestone, a strength PR, a phase-completion or phase-halfway milestone, a lifetime total — workouts, kilograms lifted, meals, or weigh-ins logged — or a sleep/recovery win). Computed automatically from the user's logs — never hand-created. Read-only.",
    },
    {
      name: "admin",
      summary:
        "Admin-only user management. An admin can list users and set another user's LLM meal-chat access, daily token limit, and admin flag — without editing the database. The first account to sign in on a fresh instance is bootstrapped as admin. Non-admin callers are rejected by the API.",
    },
  ],
  tools_by_entity: {
    user: {
      // No create: accounts are provisioned by the auth layer on first sign-in.
      read: ["get_user_profile"],
      update: ["update_user_profile"],
    },
    nutrition_phase: {
      create: ["start_nutrition_phase"],
      read: ["get_active_phase", "get_phase_history"],
      update: ["update_phase", "end_phase"],
    },
    meal: {
      create: ["log_meal"],
      read: ["get_meals", "get_macros_today", "get_macros_for_date", "get_macros_range"],
      update: ["update_meal"],
      delete: ["delete_meal"],
    },
    stored_meal: {
      create: ["define_stored_meal"],
      read: ["list_stored_meals"],
      update: ["update_stored_meal"],
      delete: ["delete_stored_meal"],
    },
    alcohol: {
      create: ["log_alcohol"],
      read: ["get_alcohol_recent"],
      update: ["update_alcohol"],
      delete: ["delete_alcohol"],
    },
    body_weight: {
      create: ["log_weight"],
      read: ["get_weight_trend"],
      update: ["update_weight"],
      delete: ["delete_weight"],
    },
    cardio: {
      create: ["log_cardio"],
      read: ["get_cardio_recent"],
      update: ["update_cardio"],
      delete: ["delete_cardio"],
    },
    sleep: {
      create: ["log_sleep"],
      read: ["get_sleep_recent"],
      update: ["update_sleep"],
      delete: ["delete_sleep"],
    },
    steps: {
      create: ["log_steps"],
      read: ["get_steps_recent"],
      update: ["update_steps"],
      delete: ["delete_steps"],
    },
    workout: {
      create: ["log_workout", "add_exercise_to_workout"],
      read: ["get_workout", "get_workout_for_day", "get_recent_workouts", "get_calendar"],
      update: ["update_workout", "update_set"],
      delete: ["delete_workout", "delete_set"],
    },
    workout_template: {
      create: ["define_workout_template"],
      read: [
        "list_workout_templates",
        "get_recommended_template",
        "get_workout_recommendation",
        "get_training_history",
      ],
      update: ["update_workout_template"],
    },
    exercise: {
      create: ["define_exercise"],
      read: ["list_exercises"],
      update: ["update_exercise"],
    },
    exercise_group: {
      create: ["define_exercise_group"],
      read: ["list_exercise_groups"],
    },
    untracked_period: {
      create: ["create_untracked_period"],
      read: ["list_untracked_periods"],
      delete: ["delete_untracked_period"],
    },
    accomplishment: {
      read: ["get_accomplishments", "get_accomplishment_history"],
    },
    admin: {
      read: ["admin_list_users"],
      update: ["admin_set_user_llm_access", "admin_set_user_daily_limit", "admin_set_user_admin"],
    },
  },
  tools_other: [
    {
      name: "log_meal_from_stored",
      summary:
        "Log a saved meal as a real eating event: copies a stored_meal's name + macros into a new meal at the given time. Pair with list_stored_meals.",
    },
    {
      name: "get_next_best_action",
      summary:
        "The recommended entrypoint. Returns the single highest-priority next action (and the ranked list) across onboarding, yesterday's forgotten sleep/steps, and today's warn/concern day-status nudges. Call at session start, after setup steps, or when the user asks 'what's next?'.",
    },
    {
      name: "get_today_context",
      summary:
        "The workhorse read. Single call returning phase + today's intake + week-to-date + TDEE + energy_balance + stim_states. Reach for this before stitching smaller reads.",
    },
    {
      name: "get_day_status",
      summary:
        "End-of-day glanceable status: today's summary + a nudges[] array (low_intake_today / no_workout_streak / stale_weight_log / stale_sleep_log / unlogged_steps) flagging patterns worth surfacing.",
    },
    {
      name: "get_tdee",
      summary:
        "Trailing TDEE estimate. basis='profile_baseline' until 14 weigh-ins accumulate; then flips to 'measured_intake'. Always caveat early-basis numbers.",
    },
    {
      name: "get_stim_state",
      summary:
        "Per-muscle-group recovery state (NOT caffeine). Drives the 'when am I due to hit X?' answer.",
    },
    {
      name: "ping",
      summary: "Liveness check. Call only after a network failure — never preventively.",
    },
    {
      name: "get_capabilities",
      summary:
        "This tool. Returns the structured catalog you're reading right now. Idempotent and free of side effects.",
    },
  ],
  common_workflows: [
    {
      name: "new_user_onboarding",
      when: "A brand-new user, or get_next_best_action reports onboarding_complete=false.",
      steps: [
        "Call get_next_best_action — it names the first unmet gate as the headline.",
        "complete_profile: confirm timezone, dob, height_cm, sex, preferred_unit_system, and activity_level via update_user_profile. The account itself already exists — it was provisioned at sign-in.",
        "log_initial_weight: log the user's current weight so TDEE can move off the formula baseline.",
        "start_nutrition_phase: if no goal stated, start a provisional maintenance phase off formula-based TDEE; note it recalibrates over ~14 days.",
        "create_workout_templates: ask the user's training split, then define_workout_template for each day.",
        "Re-call get_next_best_action after each step to advance to the next gate.",
      ],
    },
    {
      name: "log a meal the user described",
      when: "User says 'log my breakfast: 3 eggs, oats, and a banana'.",
      steps: [
        "If meal items lack amounts, ask the user OR call get_meals to find similar past entries.",
        "Compute total kcal, protein_g, carb_g, fat_g.",
        "Call log_meal with the naked-local eaten_at (or omit if 'just now').",
      ],
    },
    {
      name: "log a usual/saved meal",
      when: "User says 'log my usual breakfast' or refers to a saved meal by name.",
      steps: [
        "Call list_stored_meals to find the matching definition and its id.",
        "Call log_meal_from_stored with that id and the eaten_at (naked-local, or current time if 'just now').",
        "If the user's portion differs from the saved macros, use log_meal directly or define a new variant instead — log_meal_from_stored copies exactly.",
      ],
    },
    {
      name: "delete a duplicate workout",
      when: "User says 'I logged PUSH twice today, kill the dupe'.",
      steps: [
        "Call get_recent_workouts to enumerate today's workouts and show ids.",
        "Confirm with the user which workout_id to drop.",
        "Call delete_workout with confirm=true. The SQLite cascade removes its exercise instances and sets.",
      ],
    },
    {
      name: "answer 'how am I doing today?'",
      when: "User asks for a status check or end-of-day summary.",
      steps: [
        "Call get_day_status — returns summary + nudges in one shot.",
        "Surface warn/concern nudges proactively; mention info nudges only if relevant.",
      ],
    },
    {
      name: "log a cardio session with HR",
      when: "User says 'I ran 30 min at avg HR 150, burned ~700 kcal'.",
      steps: [
        "Call log_cardio with duration_min, avg_hr, user-reported est_kcal.",
        "Response carries kcal_estimate (HR-derived midpoint) and estimate_warning if est_kcal differs by >20%.",
        "If estimate_warning is non-null, ask the user before persisting any correction.",
      ],
    },
    {
      name: "first-time setup",
      when: "get_user_profile returns missing dob/height/sex/timezone, or get_active_phase is empty.",
      steps: [
        "Confirm timezone first — naked-local timestamps depend on it.",
        "Confirm dob, height_cm, sex (required for TDEE math). Update via update_user_profile.",
        "Confirm preferred_unit_system (metric/imperial).",
        "Suggest start_nutrition_phase with phase_type + either deficit_kcal or daily_kcal_target once the basics land. start_nutrition_phase returns a `tdee_unavailable` envelope when no body weight has been logged. Log a weight, then retry — the server computes the estimate. Pass tdee_override only when the user asserts a specific TDEE.",
        "Explain that TDEE confidence climbs over ~14 days of weigh-ins.",
      ],
    },
    {
      name: "end a phase and start a new one",
      when: "User says 'the cut is done, I'm switching to maintenance starting Monday'.",
      steps: [
        "If today is the transition day, just call start_nutrition_phase — it auto-closes the active phase the day before the new started_on.",
        "If there's a gap (e.g. ending today, new phase next week), call end_phase first with ended_on=today, then start_nutrition_phase later.",
        "Avoid update_phase for transitions — use the lifecycle tools so the intent is unambiguous in history.",
      ],
    },
  ],
};
