#!/usr/bin/env bash
# keycloak.sh — throwaway local Keycloak fixture for exercising
# ALMANAC_MCP_OIDC_ISSUER against a real, non-Google issuer. Doubles as a
# worked example of Keycloak's client/broker/flow model; almanac-realm.README.md
# is the annotated tour (the realm JSON itself can hold no comments — Keycloak
# rejects unrecognized fields on import).
#
# Usage:
#   scripts/local-dev/keycloak.sh you@example.com            # H2, ephemeral
#   scripts/local-dev/keycloak.sh you@example.com --persist  # Postgres + named volume
#   scripts/local-dev/keycloak.sh --down                     # teardown (containers + volume)
#   scripts/local-dev/keycloak.sh --print-env                # re-print the env block, no re-import
#   scripts/local-dev/keycloak.sh you@example.com --reimport # replace an existing realm
#
# Port 8085, realm "almanac". The seeded password is fixed at
# integration-dev-password: oidc.integration.test.ts hardcodes it.
#
# --persist means Postgres instead of embedded H2, so state survives a restart.
# It does NOT survive --down, which always removes the volume.
#
# NEVER commit a generated secret. Secrets are generated fresh each run with
# `openssl rand -hex 32`, substituted into a COPY of almanac-realm.json in a
# temp dir, and mounted from there — the tracked realm JSON keeps only the
# __MCP_CLIENT_SECRET__ / __WEB_CLIENT_SECRET__ placeholders.
#
# Teardown: scripts/local-dev/keycloak.sh --down
#   (stops+removes the container(s) and the docker network, removes the
#   named Postgres volume if present, and deletes the persisted secrets file.)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

# --- Fixed fixture config (not overridable — this is a test fixture, not a
# general-purpose launcher) --------------------------------------------------
KC_PORT=8085
REALM=almanac
KC_CONTAINER=almanac-dev-keycloak
PG_CONTAINER=almanac-dev-keycloak-pg
PG_VOLUME=almanac-keycloak-pgdata
KC_IMAGE="quay.io/keycloak/keycloak:26.7.1"
PG_IMAGE="postgres:16-alpine"
ADMIN_USER=admin
ADMIN_PASS=admin
DEV_USER_PASSWORD="integration-dev-password"
ISSUER="http://localhost:${KC_PORT}/realms/${REALM}"

# Where generated secrets + metadata live so --print-env and --down work on
# a later, separate invocation of this script (mirrors the /tmp/almanac-*
# throwaway-state convention used by demo.sh / dev-noauth.sh).
STATE_DIR="/tmp/almanac-keycloak"
SECRETS_FILE="$STATE_DIR/secrets.env"

# --- Args --------------------------------------------------------------------
EMAIL=""
PERSIST=0
REIMPORT=0
MODE="up"
while [ $# -gt 0 ]; do
  case "$1" in
    --persist) PERSIST=1; shift ;;
    --reimport) REIMPORT=1; shift ;;
    --down) MODE="down"; shift ;;
    --print-env) MODE="print-env"; shift ;;
    -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
    *)
      if [ -z "$EMAIL" ]; then EMAIL="$1"; shift; else echo "unknown arg: $1" >&2; exit 2; fi
      ;;
  esac
done

print_env_block() {
  if [ ! -f "$SECRETS_FILE" ]; then
    echo "ERROR: no secrets file at $SECRETS_FILE — run 'scripts/local-dev/keycloak.sh <email>' first." >&2
    exit 1
  fi
  # shellcheck disable=SC1090
  . "$SECRETS_FILE"

  # Whether console edits survive depends on the storage backend, so read the
  # mode this fixture was actually started with rather than the current flags —
  # `--print-env` is usually run in a later invocation with no --persist.
  if [ "${ALMANAC_TEST_KC_PERSIST:-0}" -eq 1 ]; then
    PERSISTENCE_NOTE="# Changes you make in the console persist across restarts (--persist mode).
#   They live in the '${PG_VOLUME}' volume and are destroyed by --down."
  else
    PERSISTENCE_NOTE="# ⚠ EPHEMERAL mode — anything you configure in the console (identity
#   providers, users, client settings) is LOST on --down or a container
#   restart. Re-run with --persist to keep it."
  fi

  cat <<EOF

# ─── Paste into .env — LOCALHOST VALUES, LOCAL USE ONLY ────────────────────
# Generated by scripts/local-dev/keycloak.sh. These secrets live only in
# $SECRETS_FILE (gitignored /tmp state) and this container's realm import —
# they are NOT in any tracked file. Re-run with --down then re-up to rotate.
ALMANAC_MCP_OIDC_ISSUER=${ISSUER}
ALMANAC_MCP_OAUTH_CLIENT_ID=almanac-mcp
ALMANAC_MCP_OAUTH_CLIENT_SECRET=${ALMANAC_TEST_KC_MCP_SECRET}
OAUTH2_PROXY_CLIENT_ID=almanac-web
OAUTH2_PROXY_CLIENT_SECRET=${ALMANAC_TEST_KC_WEB_SECRET}
# ─────────────────────────────────────────────────────────────────────────────
#
# The almanac-mcp client secret, read by oidc.integration.test.ts. Also
# sourceable directly from $SECRETS_FILE.
#   ALMANAC_TEST_KC_MCP_SECRET=${ALMANAC_TEST_KC_MCP_SECRET}
#
# Seeded user: ${ALMANAC_TEST_KC_USER:-<run without --print-env first>}
# Password:    ${DEV_USER_PASSWORD}
#
# ─── Configuring the realm by hand ───────────────────────────────────────────
# Admin console: http://localhost:${KC_PORT}  →  Administration Console
#   Username: ${ADMIN_USER}
#   Password: ${ADMIN_PASS}
#
# Use it to enable the pre-seeded (but disabled) Google/GitHub identity
# providers, add users, or inspect the account-linking flow. See
# scripts/local-dev/almanac-realm.README.md for an annotated tour.
#
${PERSISTENCE_NOTE}
#
# ⚠ Rotating a client secret in the console invalidates the .env block above —
#   the secrets there were generated at import time. Re-copy from the console,
#   or --down and re-up to regenerate both.
#
# ⚠ start-dev is NEVER production, regardless of which database backs it.
#   It disables HTTPS enforcement and hostname strictness so localhost HTTP
#   "just works" for dev — a real deployment needs Keycloak run in
#   production mode (start, not start-dev) behind TLS with a real hostname.
EOF
}

do_down() {
  echo "==> stopping and removing Keycloak fixture containers"
  docker rm -f "$KC_CONTAINER" >/dev/null 2>&1 || true
  docker rm -f "$PG_CONTAINER" >/dev/null 2>&1 || true
  if docker volume inspect "$PG_VOLUME" >/dev/null 2>&1; then
    echo "==> removing volume $PG_VOLUME"
    docker volume rm "$PG_VOLUME" >/dev/null 2>&1 || true
  fi
  docker network rm almanac-dev-keycloak-net >/dev/null 2>&1 || true
  rm -rf "$STATE_DIR"
  echo "✓ teardown complete (containers, volume, network, and $STATE_DIR removed)"
}

if [ "$MODE" = "down" ]; then
  do_down
  exit 0
fi

if [ "$MODE" = "print-env" ]; then
  print_env_block
  exit 0
fi

if [ -z "$EMAIL" ]; then
  echo "ERROR: an email argument is required (the user to seed)." >&2
  echo "Usage: scripts/local-dev/keycloak.sh you@example.com [--persist] [--reimport]" >&2
  exit 2
fi

mkdir -p "$STATE_DIR"

# --- 1. Generate secrets, substitute into a temp copy of the realm JSON ----
# Never write secrets back into the tracked almanac-realm.json.
MCP_SECRET="$(openssl rand -hex 32)"
WEB_SECRET="$(openssl rand -hex 32)"

IMPORT_DIR="$(mktemp -d)"
cleanup_import_dir() { rm -rf "$IMPORT_DIR"; }
trap cleanup_import_dir EXIT

sed \
  -e "s/__MCP_CLIENT_SECRET__/${MCP_SECRET}/" \
  -e "s/__WEB_CLIENT_SECRET__/${WEB_SECRET}/" \
  "$SCRIPT_DIR/almanac-realm.json" > "$IMPORT_DIR/almanac-realm.json"

# --- 2. Launch Keycloak (+ Postgres if --persist) ---------------------------
docker network create almanac-dev-keycloak-net >/dev/null 2>&1 || true

if [ "$PERSIST" -eq 1 ]; then
  echo "==> starting Postgres ($PG_IMAGE) with named volume $PG_VOLUME"
  docker rm -f "$PG_CONTAINER" >/dev/null 2>&1 || true
  docker run -d --rm \
    --name "$PG_CONTAINER" \
    --network almanac-dev-keycloak-net \
    -e POSTGRES_DB=keycloak \
    -e POSTGRES_USER=keycloak \
    -e POSTGRES_PASSWORD=keycloak \
    -v "${PG_VOLUME}:/var/lib/postgresql/data" \
    "$PG_IMAGE" >/dev/null

  echo "==> waiting for Postgres to accept connections"
  for i in $(seq 1 30); do
    if docker exec "$PG_CONTAINER" pg_isready -U keycloak >/dev/null 2>&1; then
      echo "    postgres up (took ${i}s)"
      break
    fi
    sleep 1
    if [ "$i" = "30" ]; then
      echo "ERROR: postgres never became ready. docker logs $PG_CONTAINER" >&2
      exit 1
    fi
  done

  DB_ARGS=(
    -e KC_DB=postgres
    -e KC_DB_URL="jdbc:postgresql://${PG_CONTAINER}/keycloak"
    -e KC_DB_USERNAME=keycloak
    -e KC_DB_PASSWORD=keycloak
  )
else
  echo "==> using embedded H2 (ephemeral — no volume, no --persist)"
  DB_ARGS=()
fi

echo "==> starting Keycloak ($KC_IMAGE) on :${KC_PORT}"
docker rm -f "$KC_CONTAINER" >/dev/null 2>&1 || true
docker run -d --rm \
  --name "$KC_CONTAINER" \
  --network almanac-dev-keycloak-net \
  -p "127.0.0.1:${KC_PORT}:8080" \
  -e KC_BOOTSTRAP_ADMIN_USERNAME="$ADMIN_USER" \
  -e KC_BOOTSTRAP_ADMIN_PASSWORD="$ADMIN_PASS" \
  "${DB_ARGS[@]}" \
  -v "$IMPORT_DIR/almanac-realm.json:/opt/keycloak/data/import/almanac-realm.json:ro" \
  "$KC_IMAGE" start-dev --import-realm >/dev/null

# --- 3. Wait for readiness ---------------------------------------------------
echo "==> waiting for Keycloak to become ready (realm discovery)"
READY=0
for i in $(seq 1 60); do
  if curl -sf "http://localhost:${KC_PORT}/realms/${REALM}/.well-known/openid-configuration" >/dev/null 2>&1; then
    echo "    keycloak up, realm '${REALM}' importable (took ${i}s)"
    READY=1
    break
  fi
  sleep 1
done
if [ "$READY" -ne 1 ]; then
  echo "ERROR: Keycloak never became ready within 60s. docker logs $KC_CONTAINER" >&2
  exit 1
fi

# --- 4. Detect an already-existing realm (the --import-realm footgun) ------
# --import-realm silently no-ops if the realm already exists (e.g. a
# --persist run reusing a volume from a previous session). Detect it via the
# admin API rather than trusting import to have happened, and tell the user
# exactly what to do instead of leaving them wondering why nothing changed.
kc_admin() {
  docker exec "$KC_CONTAINER" /opt/keycloak/bin/kcadm.sh "$@" \
    --server http://localhost:8080 \
    --realm master \
    --user "$ADMIN_USER" \
    --password "$ADMIN_PASS" \
    --config /tmp/kcadm.config
}

# kcadm needs one throwaway login before subsequent commands can omit the
# --user/--password (it caches a token in --config). Do it once up front.
docker exec "$KC_CONTAINER" /opt/keycloak/bin/kcadm.sh config credentials \
  --server http://localhost:8080 --realm master \
  --user "$ADMIN_USER" --password "$ADMIN_PASS" \
  --config /tmp/kcadm.config >/dev/null

REALM_EXISTS=0
if docker exec "$KC_CONTAINER" /opt/keycloak/bin/kcadm.sh get "realms/${REALM}" \
    --config /tmp/kcadm.config >/dev/null 2>&1; then
  REALM_EXISTS=1
fi

# We just started this container fresh (docker run, not reused), so
# REALM_EXISTS=1 here means --import-realm ran and created it OR (in
# --persist mode against a volume from a prior run) the realm already lived
# in that Postgres volume and --import-realm silently skipped re-importing
# it. Distinguish the two by checking whether the seeded secrets in the
# realm match what we just generated this run — if they don't, import was
# skipped and we're looking at stale realm state.
IMPORT_WAS_SKIPPED=0
if [ "$REALM_EXISTS" -eq 1 ] && [ "$PERSIST" -eq 1 ]; then
  EXISTING_MCP_SECRET="$(kc_admin get "clients" -r "$REALM" -q clientId=almanac-mcp --fields secret --format csv 2>/dev/null | tail -n1 | tr -d '"' || true)"
  if [ -n "$EXISTING_MCP_SECRET" ] && [ "$EXISTING_MCP_SECRET" != "$MCP_SECRET" ] && [ -f "$SECRETS_FILE" ]; then
    IMPORT_WAS_SKIPPED=1
  fi
fi

if [ "$IMPORT_WAS_SKIPPED" -eq 1 ] && [ "$REIMPORT" -ne 1 ]; then
  echo ""
  echo "⚠ Realm '${REALM}' already exists in the persisted volume '${PG_VOLUME}'."
  echo "  --import-realm silently skipped re-importing it (Keycloak does not"
  echo "  overwrite an existing realm on import), so this run's freshly"
  echo "  generated secrets were NOT applied — the realm is still using the"
  echo "  secrets from whenever it was first created."
  echo ""
  echo "  Re-print the ORIGINAL secrets:  scripts/local-dev/keycloak.sh --print-env"
  echo "  Replace the realm entirely:     scripts/local-dev/keycloak.sh $EMAIL --persist --reimport"
  echo ""
  # Keycloak is left running with the pre-existing realm; the user still has
  # a working instance, just not one matching this run's secrets. Exit 0 —
  # this is expected steady-state behavior, not a failure — but skip
  # re-seeding the user / rewriting secrets.env with wrong-for-this-realm
  # values.
  exit 0
fi

if [ "$REIMPORT" -eq 1 ] && [ "$REALM_EXISTS" -eq 1 ]; then
  echo "==> --reimport requested: deleting existing realm '${REALM}' and re-importing"
  kc_admin delete "realms/${REALM}"
  # Re-trigger import by restarting the container: --import-realm only runs
  # its import pass on Keycloak's own boot sequence, not on demand.
  docker restart "$KC_CONTAINER" >/dev/null
  echo "==> waiting for Keycloak to come back up and re-import"
  READY=0
  for i in $(seq 1 60); do
    if curl -sf "http://localhost:${KC_PORT}/realms/${REALM}/.well-known/openid-configuration" >/dev/null 2>&1; then
      READY=1
      break
    fi
    sleep 1
  done
  if [ "$READY" -ne 1 ]; then
    echo "ERROR: Keycloak never came back up after --reimport restart." >&2
    exit 1
  fi
  # kcadm's cached token/session doesn't survive the restart cleanly in all
  # versions; re-login to be safe.
  docker exec "$KC_CONTAINER" /opt/keycloak/bin/kcadm.sh config credentials \
    --server http://localhost:8080 --realm master \
    --user "$ADMIN_USER" --password "$ADMIN_PASS" \
    --config /tmp/kcadm.config >/dev/null
fi

# --- 5. Seed the user --------------------------------------------------------
# firstName/lastName are set even though nothing in this fixture displays
# them: Keycloak 26's declarative user profile marks both required for role
# "user" by default. Leaving them unset doesn't show up in the user's
# requiredActions list (that stays empty) — instead, AuthenticationProcessor
# .evaluateRequiredActionTriggers() detects the incomplete profile at LOGIN
# time and the password grant fails with invalid_grant / "Account is not
# fully set up" (verified live: this is exactly what happened before this
# was added). Set them so the seeded user is actually usable end to end.
echo "==> seeding user ${EMAIL}"
USER_ID="$(kc_admin create users -r "$REALM" \
  -s "username=${EMAIL}" \
  -s "email=${EMAIL}" \
  -s "firstName=Almanac" \
  -s "lastName=Dev" \
  -s "emailVerified=true" \
  -s "enabled=true" \
  -i 2>/dev/null || true)"

if [ -z "$USER_ID" ]; then
  # User may already exist (e.g. re-running without --reimport against a
  # fresh H2 container is impossible, but a --persist re-run without a stale
  # realm mismatch could hit this). Look it up instead of failing.
  USER_ID="$(kc_admin get users -r "$REALM" -q "username=${EMAIL}" --fields id --format csv 2>/dev/null | tail -n1 | tr -d '"' || true)"
fi

if [ -z "$USER_ID" ]; then
  echo "ERROR: could not create or find user ${EMAIL}." >&2
  exit 1
fi

kc_admin set-password -r "$REALM" --userid "$USER_ID" --new-password "$DEV_USER_PASSWORD" --temporary=false >/dev/null

# --- 6. Persist secrets + user for later --print-env / --down --------------
cat > "$SECRETS_FILE" <<EOF
# Generated by scripts/local-dev/keycloak.sh — throwaway state, not tracked in git.
ALMANAC_TEST_KC_MCP_SECRET=${MCP_SECRET}
ALMANAC_TEST_KC_WEB_SECRET=${WEB_SECRET}
ALMANAC_TEST_KC_USER=${EMAIL}
ALMANAC_TEST_KC_ISSUER=${ISSUER}
# Recorded so a later --print-env can tell you whether admin-console edits
# survive a restart (they do not in ephemeral mode).
ALMANAC_TEST_KC_PERSIST=${PERSIST}
EOF

echo ""
echo "✓ Keycloak fixture ready."
echo "  Read scripts/local-dev/almanac-realm.README.md for an annotated tour"
echo "  of the realm (clients, brokers, account-linking flow)."
print_env_block
